from django.contrib import admin
from .models import *

admin.site.register(MainMenu)
admin.site.register(MainAbout)
admin.site.register(AboutusServices)
admin.site.register(OtherAbouts)
admin.site.register(ServicesCards)
admin.site.register(CardChoose)
admin.site.register(ChooseAbout)
admin.site.register(PortfoliosType)
admin.site.register(Portfolios)
admin.site.register(TestimonialsComment)
admin.site.register(TeamMembers)
admin.site.register(MainClients)
admin.site.register(Clients)
admin.site.register(FormContact)
admin.site.register(ContactUs)
admin.site.register(CompanyName)
admin.site.register(NewsLetter)
admin.site.register(OfficialLink)
admin.site.register(FormFooter)
admin.site.register(LogoImg)