# Generated by Django 4.1 on 2022-09-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='icon_first',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='icon_second',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
