# Generated by Django 4.1 on 2022-09-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_aboutusdescription_aboutusservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='secondabout/')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='thirdabout/')),
            ],
        ),
    ]
