# Generated by Django 4.1 on 2022-09-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_cardchoose_choose'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
