# Generated by Django 4.1 on 2022-09-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_portfolios_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('img', models.ImageField(upload_to='testimonials/')),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typelar', to='main.portfoliostype'),
        ),
    ]
