# Generated by Django 4.1 on 2022-09-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_testimonialscomment_testimonialstitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='teammembers/')),
                ('profession', models.CharField(max_length=255)),
                ('youtubelink', models.CharField(max_length=999)),
                ('facebooklink', models.CharField(max_length=999)),
                ('twitterlink', models.CharField(max_length=999)),
                ('telegramlink', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
    ]
