# Generated by Django 4.1 on 2022-09-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contactus_formcontact_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.AddField(
            model_name='mainclients',
            name='link',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
    ]
