# Generated by Django 4.1 on 2022-09-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_map_mainclients_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainclients',
            name='link',
        ),
        migrations.AddField(
            model_name='contactus',
            name='link',
            field=models.CharField(default=1, max_length=999),
            preserve_default=False,
        ),
    ]
