# Generated by Django 4.1 on 2022-09-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_mainclients_link_contactus_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='link',
        ),
    ]
