# Generated by Django 4.1 on 2022-09-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_companyname_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='youtubelink',
            new_name='instagramlink',
        ),
    ]
