# Generated by Django 4.1 on 2022-09-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_youtubelink_teammembers_instagramlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutus', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('portfolio', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=255)),
                ('contactus', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramlink', models.CharField(max_length=999)),
                ('facebooklink', models.CharField(max_length=999)),
                ('twitterlink', models.CharField(max_length=999)),
                ('telegramlink', models.CharField(max_length=999)),
            ],
        ),
    ]
