# Generated by Django 4.1 on 2022-09-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_logoimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choose',
        ),
        migrations.DeleteModel(
            name='MainServices',
        ),
        migrations.DeleteModel(
            name='Navbars',
        ),
        migrations.DeleteModel(
            name='PortfolioTitle',
        ),
        migrations.DeleteModel(
            name='TeamTitles',
        ),
        migrations.DeleteModel(
            name='TestimonialsTitle',
        ),
        migrations.RemoveField(
            model_name='aboutusdescription',
            name='minitext',
        ),
        migrations.RemoveField(
            model_name='aboutusdescription',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mainclients',
            name='text',
        ),
        migrations.RemoveField(
            model_name='mainclients',
            name='title',
        ),
    ]
