# Generated by Django 4.1 on 2022-09-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_choose_delete_mainservices_delete_navbars_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='aboutdescription/')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutusDescription',
        ),
        migrations.DeleteModel(
            name='ThirdAbout',
        ),
        migrations.RenameModel(
            old_name='SecondAbout',
            new_name='OtherAbouts',
        ),
        migrations.AddField(
            model_name='mainabout',
            name='abouts',
            field=models.ManyToManyField(to='main.otherabouts'),
        ),
    ]
